/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import br.com.solugem.model.AcumuloServico;
import br.com.solugem.model.Cargo;
import br.com.solugem.model.Cliente;
import br.com.solugem.model.Empresa;
import br.com.solugem.model.Endereco;
import br.com.solugem.model.Funcionario;
import br.com.solugem.model.Telefone;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import solugemmDao.ClienteDao;
import solugemmDao.FuncionarioDao;

/**
 *
 * @author principal
 */
public class CadastroClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroClientes.class.getName());

   // private char privilegio;
    public CadastroClientes() {
        initComponents();
         model();
         txtPesquisarCPFCliente.setText("10340440444");
    }
    char privilegio;
    public CadastroClientes(char inicial){
        this();
        privilegio = inicial;
       
         switch (inicial) {
                case '2':
                System.out.println("Acesso: DONO");
                       
                break;
        
                case '1':
                System.out.println("Acesso: ATENDENTE");
                btnExcluirCliente.setEnabled(false);
                
                
                
                break;
        
           }
    
    }
   int  idCliente = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel18 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        btnTelaCadastroMateriais = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        btnTelaOs = new javax.swing.JButton();
        btnTelaCadastroServicos = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnTelaCadastroFuncionarios = new javax.swing.JButton();
        tabelaClientes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCasa = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtApartamento = new javax.swing.JTextField();
        txtBloco = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnSalvarCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        table = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        btnExcluirCliente = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPesquisarCPFCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel17.setBackground(new java.awt.Color(0, 0, 51));
        jPanel17.setPreferredSize(new java.awt.Dimension(153, 700));

        jLabel38.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Gestão");

        jLabel39.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));

        btnTelaCadastroMateriais.setBackground(new java.awt.Color(0, 0, 51));
        btnTelaCadastroMateriais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTelaCadastroMateriais.setForeground(new java.awt.Color(255, 255, 255));
        btnTelaCadastroMateriais.setText("<html>Cadastro de<br>Materiais");
        btnTelaCadastroMateriais.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTelaCadastroMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20jButton1ActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(0, 0, 51));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Início");
        btnInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21jButton2ActionPerformed(evt);
            }
        });

        jButton46.setBackground(new java.awt.Color(0, 0, 51));
        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton46.setForeground(new java.awt.Color(255, 255, 255));
        jButton46.setText("<html>Cadastro de<br>Clinetes");
        jButton46.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22jButton3ActionPerformed(evt);
            }
        });

        btnTelaOs.setBackground(new java.awt.Color(0, 0, 51));
        btnTelaOs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTelaOs.setForeground(new java.awt.Color(255, 255, 255));
        btnTelaOs.setText("<html>Ordem de<br>Serviços");
        btnTelaOs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTelaOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23jButton4ActionPerformed(evt);
            }
        });

        btnTelaCadastroServicos.setBackground(new java.awt.Color(0, 0, 51));
        btnTelaCadastroServicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTelaCadastroServicos.setForeground(new java.awt.Color(255, 255, 255));
        btnTelaCadastroServicos.setText("<html>Cadastro de<br>Serviços");
        btnTelaCadastroServicos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTelaCadastroServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24jButton5ActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(204, 0, 0));
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnTelaCadastroFuncionarios.setBackground(new java.awt.Color(0, 0, 51));
        btnTelaCadastroFuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTelaCadastroFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        btnTelaCadastroFuncionarios.setText("<html>Cadastro de<br>Funcionários");
        btnTelaCadastroFuncionarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTelaCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaCadastroFuncionariosjButton21jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addComponent(btnTelaCadastroServicos)
                .addContainerGap())
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38))
                    .addComponent(btnTelaOs, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTelaCadastroMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTelaCadastroFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel17Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInicio)
                        .addGap(18, 18, 18)
                        .addComponent(btnTelaCadastroFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnTelaCadastroMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTelaCadastroServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTelaOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(btnSair)
                .addContainerGap(567, Short.MAX_VALUE))
        );

        tabelaClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Novo Cliente");

        jLabel6.setText("Nome completo");

        jLabel7.setText("Telefone");

        jLabel8.setText("Email");

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.setPreferredSize(new java.awt.Dimension(30, 27));

        jLabel9.setText("Data de Nascimento");

        jLabel10.setText("CPF");

        jLabel12.setText("Sexo");

        jLabel15.setText("Endereço");

        jLabel16.setText("CEP");

        jLabel17.setText("Bairro");

        jLabel18.setText("Cidade");

        jLabel20.setText("Rua");

        jLabel21.setText("Número");

        jLabel22.setText("Casa");

        jLabel23.setText("Apartamento");

        jLabel24.setText("Bloco");

        btnAtualizar.setBackground(new java.awt.Color(0, 0, 102));
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar ");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado");

        jLabel11.setText("Editar dados");

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnSalvarCliente.setBackground(new java.awt.Color(153, 0, 153));
        btnSalvarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarCliente.setText("Salvar Cliente");
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabelaClientesLayout = new javax.swing.GroupLayout(tabelaClientes);
        tabelaClientes.setLayout(tabelaClientesLayout);
        tabelaClientesLayout.setHorizontalGroup(
            tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaClientesLayout.createSequentialGroup()
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabelaClientesLayout.createSequentialGroup()
                                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                        .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tabelaClientesLayout.createSequentialGroup()
                                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5))
                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(txtApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabelaClientesLayout.createSequentialGroup()
                                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)))
                                .addGap(0, 62, Short.MAX_VALUE))
                            .addGroup(tabelaClientesLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(btnAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))))
                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabelaClientesLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btnSalvarCliente)
                    .addContainerGap(727, Short.MAX_VALUE)))
        );
        tabelaClientesLayout.setVerticalGroup(
            tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaClientesLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jButton3))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelaClientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtualizar)
                        .addGap(30, 30, 30))))
            .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelaClientesLayout.createSequentialGroup()
                    .addContainerGap(625, Short.MAX_VALUE)
                    .addComponent(btnSalvarCliente)
                    .addGap(29, 29, 29)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel31.setText("Funcionários cadastrados");

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Email", "Telefone", "CPF"
            }
        ));
        table.setViewportView(tabelaCliente);

        btnExcluirCliente.setBackground(new java.awt.Color(255, 51, 51));
        btnExcluirCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        jLabel13.setText("Selecione uma linha");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirCliente))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel31)
                        .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirCliente)
                    .addComponent(jLabel13))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cadastro de clientes");

        jLabel4.setText("Gerencie os clientes");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtPesquisarCPFCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisarCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarCPFClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisar Cliente  por CPF");

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Novo Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisarCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(tabelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 155, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(txtPesquisarCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
       
        String strNome = txtNome.getText();
        String strTelefone = txtTelefone.getText();
        String strEmail = txtEmail.getText();
        String strCPF = txtCPF.getText();
        String strSexo = txtSexo.getText();
        String strData = "";
        
 
        try{
            txtDataNascimento.commitEdit();
            strData = txtDataNascimento.getText().trim();
        }catch(java.text.ParseException e){
            JOptionPane.showMessageDialog(null, "Digite a data correta");
        }
        
        String cep = txtCEP.getText();
        String bairro = txtBairro.getText();
        String cidade = txtCidade.getText();
        String estado = txtEstado.getText();
        String rua = txtRua.getText();
        String numero = txtNumero.getText();
        String casa = txtCasa.getText();
        String apartamento = txtApartamento.getText();
        String bloco = txtBloco.getText();
        
        Cliente cliente = new Cliente();
        Endereco endereco = new Endereco();
        Telefone telefone = new Telefone();
        ClienteDao dao = new ClienteDao();
        
       
        
        if(strNome.trim().isEmpty() || strTelefone.trim().isEmpty() 
        || strCPF.trim().isEmpty() || strSexo.trim().isEmpty()||cep.trim().isEmpty()||bairro.trim().isEmpty()
        ||cidade.trim().isEmpty()||estado.trim().isEmpty()||rua.trim().isEmpty()||numero.trim().isEmpty()
        ){
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos");
         return;   
        }
         if (!numero.matches("^(?i)(SN|[0-9]+[\\s-]?[A-Za-z]?)$")) {
            JOptionPane.showMessageDialog(this,"Erro! Por favor, insira um número válido (ex: 123, 123-A ou SN)");
            return;
        }
        
        if (!strTelefone.matches("^[0-9]{10,11}$")) {
             JOptionPane.showMessageDialog(this, "O telefone deve conter apenas números (DDD + número) e ter entre 10 e 11 dígitos.");
             return;
        } 
        if (!strData.matches("^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/[0-9]{4}$")) {
            JOptionPane.showMessageDialog(this,"Data inválida");
            return;
        }
        if (!strCPF.matches("^[0-9]{11}$")) {
              JOptionPane.showMessageDialog(this,"CPF inválido");
            return;
        }
        if (!cep.matches("^[0-9]{5}-?[0-9]{3}$")) {
           JOptionPane.showMessageDialog(this, "CEP inválido! Use o formato 00000-000.");
           return;
        }
        if (!strSexo.matches("^[MmFf]$")) {
          JOptionPane.showMessageDialog(this, "Sexo inválido! Digite apenas M ou F.");
          return;
       }
        
        try{
        endereco.setCep(cep);
        endereco.setBairro(bairro);
        endereco.setCidade(cidade);
        endereco.setEstado(estado);
        endereco.setRua(rua);
       // endereco.setNumero(Integer.parseInt(numero));
        endereco.setNumero(numero);
        endereco.setCasa(casa);
        endereco.setNumeroApartamento(apartamento);
        endereco.setBloco(bloco);
        
       // telefone.setNumero(strTelefone);
        
        cliente.setIdCliente(idCliente);
        cliente.setNome(strNome);
        cliente.setEmail(strEmail);
        DateTimeFormatter formatadorBR = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNascimento = LocalDate.parse(strData,formatadorBR);
        cliente.setDataNascimento(dataNascimento);
        cliente.setCPF(strCPF);
        cliente.setTel(strTelefone);
        cliente.setSexo(strSexo);
        cliente.setEndereco(endereco);
        cliente.setTelefone(telefone);
        cliente.setEndereco(endereco);
        
        dao.atualizar(cliente);
        idCliente = 0;
       // model();
        JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso");
        }catch(Exception e){
              e.printStackTrace();
              JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
           // JOptionPane.showMessageDialog(this,"Erro inesperado, Cliente não cadastrado");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void jButton24jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24jButton5ActionPerformed
        CadastroServicos cadServ = new CadastroServicos(privilegio);
        cadServ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton24jButton5ActionPerformed

    private void jButton23jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23jButton4ActionPerformed
        TelaOrdemServico os = new TelaOrdemServico(privilegio);
        os.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton23jButton4ActionPerformed

    private void jButton22jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22jButton3ActionPerformed
                  
    }//GEN-LAST:event_jButton22jButton3ActionPerformed

    private void jButton21jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21jButton2ActionPerformed
        Home home = new Home(privilegio);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton21jButton2ActionPerformed

    private void jButton20jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20jButton1ActionPerformed
        CadastroMaterial cadMat = new CadastroMaterial(privilegio);
        cadMat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton20jButton1ActionPerformed

    private void btnTelaCadastroFuncionariosjButton21jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaCadastroFuncionariosjButton21jButton2ActionPerformed
        CadastroFuncionarios cadFunc = new CadastroFuncionarios(privilegio);
        cadFunc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTelaCadastroFuncionariosjButton21jButton2ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String strPesquisarCPFCliente = txtPesquisarCPFCliente.getText();
        
        
        ClienteDao dao = new ClienteDao();
        Cliente cliente = dao.consultar(strPesquisarCPFCliente);
        
        if(cliente == null){
            JOptionPane.showMessageDialog(this, "Cliente não encontrado");
        }else{
        idCliente = cliente.getIdCliente();
        txtNome.setText(cliente.getNome());
       // txtTelefone.setText(cliente.getTelefone().getNumero());
        txtTelefone.setText(cliente.getTel());
        txtEmail.setText(cliente.getEmail());
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtDataNascimento.setText(cliente.getDataNascimento().format(formatador));
       // txtDataNascimento.setText(cliente.getDataNascimento().toString());
        txtCPF.setText(cliente.getCPF());
        txtSexo.setText(cliente.getSexo());
        txtCEP.setText(cliente.getEndereco().getCep());
        txtBairro.setText(cliente.getEndereco().getBairro());
        txtCidade.setText(cliente.getEndereco().getCidade());
        txtEstado.setText(cliente.getEndereco().getEstado());
        txtRua.setText(cliente.getEndereco().getRua());
        txtNumero.setText(String.valueOf(cliente.getEndereco().getNumero()));
        txtCasa.setText(cliente.getEndereco().getCasa());
        txtApartamento.setText(cliente.getEndereco().getNumeroApartamento());
        txtBloco.setText(cliente.getEndereco().getBloco());
        
        btnSalvarCliente.setEnabled(false);
        
      //  txtPesquisarCPFCliente.setEditable(false);
        txtNome.setEditable(false);
        txtTelefone.setEditable(false);
        txtEmail.setEditable(false);
        txtDataNascimento.setEditable(false);
        txtCPF.setEditable(false);
        txtSexo.setEditable(false);
        txtCEP.setEditable(false);
        txtBairro.setEditable(false);
        txtCidade.setEditable(false);
        txtEstado.setEditable(false);
        txtRua.setEditable(false);
        txtNumero.setEditable(false);
        txtCasa.setEditable(false);
        txtApartamento.setEditable(false);
        txtBloco.setEditable(false);
         
     }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtPesquisarCPFCliente.setEditable(true);
        txtNome.setEditable(true);
        txtTelefone.setEditable(true);
        txtEmail.setEditable(true);
        txtDataNascimento.setEditable(true);
        txtCPF.setEditable(true);
        txtSexo.setEditable(true);
        txtCEP.setEditable(true);
        txtBairro.setEditable(true);
        txtCidade.setEditable(true);
        txtEstado.setEditable(true);
        txtRua.setEditable(true);
        txtNumero.setEditable(true);
        txtCasa.setEditable(true);
        txtApartamento.setEditable(true);
        txtBloco.setEditable(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
        String strNome = txtNome.getText();
        String strTelefone = txtTelefone.getText();
        String strEmail = txtEmail.getText();
        String strCPF = txtCPF.getText();
        String strSexo = txtSexo.getText();
        String strData = "";
        
 
        try{
            txtDataNascimento.commitEdit();
            strData = txtDataNascimento.getText().trim();
        }catch(java.text.ParseException e){
            JOptionPane.showMessageDialog(null, "Digite a data correta");
        }
        
        String cep = txtCEP.getText();
        String bairro = txtBairro.getText();
        String cidade = txtCidade.getText();
        String estado = txtEstado.getText();
        String rua = txtRua.getText();
        String numero = txtNumero.getText();
        String casa = txtCasa.getText();
        String apartamento = txtApartamento.getText();
        String bloco = txtBloco.getText();
        
        Cliente cliente = new Cliente();
        Endereco endereco = new Endereco();
        Telefone telefone = new Telefone();
        ClienteDao dao = new ClienteDao();
        
       
        
        if(strNome.trim().isEmpty() || strTelefone.trim().isEmpty() 
        || strCPF.trim().isEmpty() || strSexo.trim().isEmpty()||cep.trim().isEmpty()||bairro.trim().isEmpty()
        ||cidade.trim().isEmpty()||estado.trim().isEmpty()||rua.trim().isEmpty()||numero.trim().isEmpty()
        ){
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos");
         return;   
        }
         if (!numero.matches("^(?i)(SN|[0-9]+[\\s-]?[A-Za-z]?)$")) {
            JOptionPane.showMessageDialog(this,"Erro! Por favor, insira um número válido (ex: 123, 123-A ou SN)");
            return;
        }
        
        if (!strTelefone.matches("^[0-9]{10,11}$")) {
             JOptionPane.showMessageDialog(this, "O telefone deve conter apenas números (DDD + número) e ter entre 10 e 11 dígitos.");
             return;
        } 
        if (!strData.matches("^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/[0-9]{4}$")) {
            JOptionPane.showMessageDialog(this,"Data inválida");
            return;
        }
        if (!strCPF.matches("^[0-9]{11}$")) {
              JOptionPane.showMessageDialog(this,"CPF inválido");
            return;
        }
        if (!cep.matches("^[0-9]{5}-?[0-9]{3}$")) {
           JOptionPane.showMessageDialog(this, "CEP inválido! Use o formato 00000-000.");
           return;
        }
        if (!strSexo.matches("^[MmFf]$")) {
          JOptionPane.showMessageDialog(this, "Sexo inválido! Digite apenas M ou F.");
          return;
        }
        
        try{
        endereco.setCep(cep);
        endereco.setBairro(bairro);
        endereco.setCidade(cidade);
        endereco.setEstado(estado);
        endereco.setRua(rua);
       // endereco.setNumero(Integer.parseInt(numero));
        endereco.setNumero(numero);
        endereco.setCasa(casa);
        endereco.setNumeroApartamento(apartamento);
        endereco.setBloco(bloco);
        
       // telefone.setNumero(strTelefone);
        
        cliente.setNome(strNome);
        cliente.setEmail(strEmail);
        DateTimeFormatter formatadorBR = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNascimento = LocalDate.parse(strData,formatadorBR);
        cliente.setDataNascimento(dataNascimento);
        cliente.setCPF(strCPF);
        cliente.setSexo(strSexo);
        cliente.setEndereco(endereco);
       // cliente.setTelefone(telefone);
       cliente.setTel(strTelefone);
        cliente.setEndereco(endereco);
        
        dao.salvar(cliente);
       // model();
        JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso");
        }catch(Exception e){
            e.printStackTrace(); 
             JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
          // JOptionPane.showMessageDialog(this, "Erro inesperado, cadastro não realizado");
        } 
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        int linhaSelecionada = tabelaCliente.getSelectedRow();
         ClienteDao dao = new ClienteDao();
           
           if (linhaSelecionada >= 0) {
        
                 int idCliente = (int) tabelaCliente.getValueAt(linhaSelecionada, 0);
                 int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir esta consulta?");
            
            if (resposta == JOptionPane.YES_OPTION) {
         
                dao.remover(idCliente);
                 
              //  model();
                
            JOptionPane.showMessageDialog(this, "Item excluido com sucesso!");
            }
        
    } else {
        
        JOptionPane.showMessageDialog(this, "Selecione uma consulta na tabela para excluir.");
    }
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtPesquisarCPFCliente.setEditable(true);
        txtNome.setEditable(true);
        txtTelefone.setEditable(true);
        txtEmail.setEditable(true);
        txtDataNascimento.setEditable(true);
        txtCPF.setEditable(true);
        txtSexo.setEditable(true);
        txtCEP.setEditable(true);
        txtBairro.setEditable(true);
        txtCidade.setEditable(true);
        txtEstado.setEditable(true);
        txtRua.setEditable(true);
        txtNumero.setEditable(true);
        txtCasa.setEditable(true);
        txtApartamento.setEditable(true);
        txtBloco.setEditable(true);
        
        txtPesquisarCPFCliente.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtDataNascimento.setText("");
        txtCPF.setText("");
        txtSexo.setText("");
        txtCEP.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtCasa.setText("");
        txtApartamento.setText("");
        txtBloco.setText("");
        
        btnSalvarCliente.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPesquisarCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarCPFClienteActionPerformed

     /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroClientes().setVisible(true));
    } 
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JButton btnTelaCadastroFuncionarios;
    private javax.swing.JButton btnTelaCadastroMateriais;
    private javax.swing.JButton btnTelaCadastroServicos;
    private javax.swing.JButton btnTelaOs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton46;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JPanel tabelaClientes;
    private javax.swing.JScrollPane table;
    private javax.swing.JTextField txtApartamento;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBloco;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCasa;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisarCPFCliente;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    
    public void model() {
    DefaultTableModel model = (DefaultTableModel) tabelaCliente.getModel();
    ClienteDao dao = new ClienteDao();
    List<Cliente> lista = dao.consultarTodos();
    
  
    if (lista == null || lista.isEmpty()) {
        System.out.println("DEBUG: A lista retornada pelo DAO está vazia.");
        return; 
    }
    
    model.setRowCount(0);
    
    for (Cliente c : lista) {
        model.addRow(new Object[]{
            c.getIdCliente(),
            c.getNome(),
            c.getEmail(),
            c.getTel(),
            c.getCPF()
            
        });
    }
    tabelaCliente.getColumnModel().getColumn(0).setMinWidth(0);
    tabelaCliente.getColumnModel().getColumn(0).setMaxWidth(0);
    tabelaCliente.getColumnModel().getColumn(0).setPreferredWidth(0);
}   

}
