/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import br.com.solugem.model.Fabricante;
import br.com.solugem.model.Funcionario;
import br.com.solugem.model.Material;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import solugemmDao.FuncionarioDao;
import solugemmDao.MaterialDao;

/**
 *
 * @author principal
 */
public class CadastroMaterial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroMaterial.class.getName());

    /**
     * Creates new form CadastroMaterial
     */
    public CadastroMaterial() {
        initComponents();
         model();
         txtPesquisar.setText("1125");
    }
    char privilegio;
    public CadastroMaterial(char inicial){
        this();
        privilegio = inicial;
         switch (inicial) {
                case '2':
                System.out.println("Acesso: DONO");
                       
                break;
        
                case '1':
                // privilégios para atendentes estabelecidos pela documentação 
                System.out.println("Acesso: ATENDENTE");
                btnSalvarMaterial.setEnabled(false);
                btnNovoMaterial.setEnabled(false);
                btnAtualizar.setEnabled(false);
                btnEditar.setEnabled(false);
                btnExcluir.setEnabled(false);
                break;
        
           }
            
    }
    int idMaterial = 0;
    int idFabricante = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel18 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        tabelaClientes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtFabricante = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        btnSalvarMaterial = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaMaterial = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnNovoMaterial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel17.setBackground(new java.awt.Color(0, 0, 51));

        jLabel38.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Gestão");

        jLabel39.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));

        jButton44.setBackground(new java.awt.Color(0, 0, 51));
        jButton44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton44.setForeground(new java.awt.Color(255, 255, 255));
        jButton44.setText("<html>Cadastro de<br>Materiais");
        jButton44.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44jButton20jButton1ActionPerformed(evt);
            }
        });

        jButton45.setBackground(new java.awt.Color(0, 0, 51));
        jButton45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton45.setForeground(new java.awt.Color(255, 255, 255));
        jButton45.setText("<html>Cadastro de<br>Funcionários");
        jButton45.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45jButton21jButton2ActionPerformed(evt);
            }
        });

        jButton46.setBackground(new java.awt.Color(0, 0, 51));
        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton46.setForeground(new java.awt.Color(255, 255, 255));
        jButton46.setText("<html>Cadastro de<br>Clinetes");
        jButton46.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46jButton22jButton3ActionPerformed(evt);
            }
        });

        jButton47.setBackground(new java.awt.Color(0, 0, 51));
        jButton47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton47.setForeground(new java.awt.Color(255, 255, 255));
        jButton47.setText("<html>Ordem de<br>Serviços");
        jButton47.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47jButton23jButton4ActionPerformed(evt);
            }
        });

        jButton48.setBackground(new java.awt.Color(0, 0, 51));
        jButton48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton48.setForeground(new java.awt.Color(255, 255, 255));
        jButton48.setText("<html>Cadastro de<br>Serviços");
        jButton48.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48jButton24jButton5ActionPerformed(evt);
            }
        });

        jButton49.setBackground(new java.awt.Color(204, 0, 0));
        jButton49.setForeground(new java.awt.Color(255, 255, 255));
        jButton49.setText("Sair");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(0, 0, 51));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Início");
        btnInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciojButton21jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(16, 16, 16))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38))
                    .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                    .addComponent(jButton48, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(jButton49)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(599, Short.MAX_VALUE)))
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(308, 308, 308)
                    .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(448, Short.MAX_VALUE)))
        );

        tabelaClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Novo Material");

        jLabel6.setText("Nome do Material");

        jLabel7.setText("Preço");

        jLabel8.setText("Código");

        jLabel9.setText("Nome Fábricante");

        jLabel17.setText("CNPJ");

        jLabel19.setText("Estado");

        btnSalvarMaterial.setBackground(new java.awt.Color(153, 0, 153));
        btnSalvarMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarMaterial.setText("Salvar Material");
        btnSalvarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarMaterialActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(0, 102, 0));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel2.setText("Editar dados");

        btnAtualizar.setBackground(new java.awt.Color(0, 0, 204));
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabelaClientesLayout = new javax.swing.GroupLayout(tabelaClientes);
        tabelaClientes.setLayout(tabelaClientesLayout);
        tabelaClientesLayout.setHorizontalGroup(
            tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaClientesLayout.createSequentialGroup()
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5))
                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                        .addGap(607, 607, 607)
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabelaClientesLayout.createSequentialGroup()
                                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabelaClientesLayout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(btnSalvarMaterial)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAtualizar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEditar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabelaClientesLayout.createSequentialGroup()
                                    .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabelaClientesLayout.setVerticalGroup(
            tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaClientesLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarMaterial)
                    .addComponent(btnEditar)
                    .addComponent(jLabel2)
                    .addComponent(btnAtualizar))
                .addGap(144, 144, 144)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel31.setText("Materiais em estoque");

        tabelaMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idMaterial", "Código", "Nome", "Preço", "Fabricante"
            }
        ));
        jScrollPane3.setViewportView(tabelaMaterial);

        btnExcluir.setBackground(new java.awt.Color(255, 0, 51));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel25.setText("Selecionar uma linha");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cadastro de Material");

        jLabel4.setText("Gerencie o estoque de  materiais");

        btnPesquisar.setBackground(new java.awt.Color(102, 102, 102));
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar material por código");

        btnNovoMaterial.setBackground(new java.awt.Color(51, 51, 255));
        btnNovoMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoMaterial.setText("Novo Material");
        btnNovoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel18Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPesquisar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNovoMaterial))
                        .addGroup(jPanel18Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tabelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnNovoMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(403, 403, 403))
        );

        jScrollPane1.setViewportView(jPanel18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1071, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton44jButton20jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44jButton20jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton44jButton20jButton1ActionPerformed

    private void jButton45jButton21jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45jButton21jButton2ActionPerformed
        CadastroFuncionarios func = new CadastroFuncionarios(privilegio);
        func.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton45jButton21jButton2ActionPerformed

    private void jButton46jButton22jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46jButton22jButton3ActionPerformed
        CadastroClientes cli = new CadastroClientes(privilegio);
        cli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton46jButton22jButton3ActionPerformed

    private void jButton47jButton23jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47jButton23jButton4ActionPerformed
       TelaOrdemServico os = new TelaOrdemServico(privilegio);
       os.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton47jButton23jButton4ActionPerformed

    private void jButton48jButton24jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48jButton24jButton5ActionPerformed
        CadastroServicos cadServ = new CadastroServicos(privilegio);
        cadServ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton48jButton24jButton5ActionPerformed

    private void btnSalvarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMaterialActionPerformed
        String strNome = txtNome.getText();
        String strPreco = txtPreco.getText();
        String strCodigo = txtCodigo.getText();
        String strFabricante = txtFabricante.getText();
        String strCNPJ = txtCNPJ.getText().trim();
        
        if(strNome.trim().isEmpty() || strPreco.trim().isEmpty() || strCodigo.trim().isEmpty() || strFabricante.trim().isEmpty() || strCNPJ.trim().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Todos os campos obrigatórios devem ser preenchidos");
            return;
        }
        
        if (!strPreco.matches("^[0-9]+(,[0-9]{1,2})?$")) {
             JOptionPane.showMessageDialog(this, "Formato inválido! Use formato: 0,00");
             return; 
        }
         String limpo = strPreco.replace(".", "").replace(",", ".");
        if (!strCNPJ.matches("^[0-9]{14}$")) {
              JOptionPane.showMessageDialog(this,"CNPJ inválido, digite 14 caracteres de 0 a 9");
            return;
        }
        if (!strCodigo.matches("^[0-9]{4}$")) {
              JOptionPane.showMessageDialog(this,"Código Invalido, digite digite 4 caracteres de 0 a 9");
            return;
        }
        
        MaterialDao dao = new MaterialDao();
        Fabricante fab = new Fabricante();
        Material mat = new Material();
        
        mat.setNome(strNome);
        try {
              mat.setPreco(Double.parseDouble(limpo));
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ocorreu um erro na conersão do preço!");
          return;
        }
      try{
        mat.setCodigo(strCodigo);
        
        fab.setNome(strFabricante);
        fab.setCnpj(strCNPJ);
        
        mat.setFabricante(fab);
        
        dao.salvarMaterialComFabricante(mat);
        
        model();
        JOptionPane.showMessageDialog(this, "Material cadastrado com sucesso");
      }catch(Exception e){
          JOptionPane.showMessageDialog(this, "Erro inesperado, material não cadastrado");
      }    
    }//GEN-LAST:event_btnSalvarMaterialActionPerformed

    private void btnIniciojButton21jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciojButton21jButton2ActionPerformed
        Home home = new Home(privilegio);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciojButton21jButton2ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton49ActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void btnNovoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoMaterialActionPerformed
        txtPesquisar.setEditable(true);
        txtNome.setEditable(true);
        txtPreco.setEditable(true);
        txtCodigo.setEditable(true);
        txtFabricante.setEditable(true);
        txtCNPJ.setEditable(true);
        
        
        txtPesquisar.setText("");
        txtNome.setText("");
        txtPreco.setText("");
        txtCodigo.setText("");
        txtFabricante.setText("");
        txtCNPJ.setText("");
      
        btnSalvarMaterial.setEnabled(true);        
    }//GEN-LAST:event_btnNovoMaterialActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtPesquisar.setEditable(true);
        txtNome.setEditable(true);
        txtPreco.setEditable(true);
        txtCodigo.setEditable(true);
        txtFabricante.setEditable(true);
        txtCNPJ.setEditable(true);
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        String strNome = txtNome.getText();
        String strPreco = txtPreco.getText();
        String strCodigo = txtCodigo.getText();
        String strFabricante = txtFabricante.getText();
        String strCNPJ = txtCNPJ.getText();
        
        if(strNome.trim().isEmpty() || strPreco.trim().isEmpty() || strCodigo.trim().isEmpty() || strFabricante.trim().isEmpty() || strCNPJ.trim().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Todos os campos obrigatórios devem ser preenchidos");
            return;
        }
        
        if (!strPreco.matches("^[0-9]+(,[0-9]{1,2})?$")) {
             JOptionPane.showMessageDialog(this, "Formato inválido! Use formato: 0,00");
             return; 
        }
         String limpo = strPreco.replace(".", "").replace(",", ".");
        if (!strCNPJ.matches("^[0-9]{14}$")) {
              JOptionPane.showMessageDialog(this,"CNPJ inválido, digite 14 caracteres de 0 a 9");
            return;
        }
        if (!strCodigo.matches("^[0-9]{4}$")) {
              JOptionPane.showMessageDialog(this,"Código Invalido, digite digite 4 caracteres de 0 a 9");
            return;
        }
        
         MaterialDao dao = new MaterialDao();
        Fabricante fab = new Fabricante();
        Material mat = new Material();
        
        mat.setNome(strNome);
        try {
              mat.setPreco(Double.parseDouble(limpo));
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ocorreu um erro na conersão do preço!");
          return;
        }
     try{  
        mat.setCodigo(strCodigo);
        mat.setIdMaterial(idMaterial);
        
        fab.setNome(strFabricante);
        fab.setCnpj(strCNPJ);
        fab.setIdFabricante(idFabricante);
        
        mat.setFabricante(fab);
        
        dao.atualizar(mat);
        
        model();
        JOptionPane.showMessageDialog(this, "Material atualizado com sucesso");
     }catch(Exception e){
         JOptionPane.showMessageDialog(this, "Erro inesperado, material não atualizado");
     }   

        
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = tabelaMaterial.getSelectedRow();
        MaterialDao dao = new MaterialDao();

        if (linhaSelecionada >= 0) {
            
            int idMaterial = (int) tabelaMaterial.getValueAt(linhaSelecionada, 0);
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir esta consulta?");

            if (resposta == JOptionPane.YES_OPTION) {

                dao.remover(idMaterial);

                model();

                JOptionPane.showMessageDialog(this, "Item excluido com sucesso!");
            }

        } else {

            JOptionPane.showMessageDialog(this, "Selecione uma consulta na tabela para excluir.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
         String strPesquisar = txtPesquisar.getText();
        
        
        MaterialDao dao = new MaterialDao();
        Material material = dao.consultar(strPesquisar);
        
        if(material == null){
            JOptionPane.showMessageDialog(this, "Material não encontrado");
        }else{
        idMaterial = material.getIdMaterial();
        idFabricante = material.getFabricante().getIdFabricante();
        txtNome.setText(material.getNome());
       
        txtPreco.setText(String.valueOf(material.getPreco()));
      
        txtCodigo.setText(material.getCodigo());
        txtFabricante.setText(material.getFabricante().getNome());
        txtCNPJ.setText(material.getFabricante().getCnpj());
      
       
        btnSalvarMaterial.setEnabled(false);
        
       // txtPesquisar.setEditable(false);
        txtNome.setEditable(false);
        txtPreco.setEditable(false);
        txtCodigo.setEditable(false);
        txtFabricante.setEditable(false);
        txtCNPJ.setEditable(false);
        
         
     }        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroMaterial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnNovoMaterial;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvarMaterial;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JPanel tabelaClientes;
    private javax.swing.JTable tabelaMaterial;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtFabricante;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables

public void model() {
    DefaultTableModel model = (DefaultTableModel) tabelaMaterial.getModel();
    MaterialDao dao = new MaterialDao();
    List<Material> lista = dao.consultarTodos();
    
   
    if (lista == null || lista.isEmpty()) {
        System.out.println("DEBUG: A lista retornada pelo DAO está vazia.");
        return; 
    }
    
    model.setRowCount(0);
    DecimalFormat df = new DecimalFormat("#,##0.00");
    for (Material m : lista) {
        
        model.addRow(new Object[]{
            m.getIdMaterial(),
            m.getCodigo(),
            m.getNome(),
            df.format(m.getPreco()),
            m.getFabricante().getNome()
        });
    }
    tabelaMaterial.getColumnModel().getColumn(0).setMinWidth(0);
    tabelaMaterial.getColumnModel().getColumn(0).setMaxWidth(0);
    tabelaMaterial.getColumnModel().getColumn(0).setPreferredWidth(0);    


}


}