/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import br.com.solugem.model.Material;
import br.com.solugem.model.TipoDeServico;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import solugemmDao.MaterialDao;
import solugemmDao.TipoDeServicoDao;

/**
 *
 * @author principal
 */
public class CadastroServicos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroServicos.class.getName());

    /**
     * Creates new form CadastroServicos
     */
    public CadastroServicos() {
        initComponents();
        txtPesquisarServico.setText("2545");
        model();
    }
    char privilegio;
    public CadastroServicos(char inicial){
        this();
        privilegio = inicial;
         switch (inicial) {
                case '2':
                System.out.println("Acesso: DONO");
                       
                break;
        
                case '1':
                System.out.println("Acesso: ATENDENTE");
                // privilégios para atendentes estabelecidos pela documentação 
                btnSalvarServico.setEnabled(false);
                btnNovoServico.setEnabled(false);
                btnAtualizar.setEnabled(false);
                btnEditar.setEnabled(false);
                btnExcluir.setEnabled(false);
                break;
        
           }
            
    }
     int idtds = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel18 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        tabelaClientes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        btnSalvarServico = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaServicos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisarServico = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnNovoServico = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel17.setBackground(new java.awt.Color(0, 0, 51));

        jLabel38.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Gestão");

        jLabel39.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));

        jButton44.setBackground(new java.awt.Color(0, 0, 51));
        jButton44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton44.setForeground(new java.awt.Color(255, 255, 255));
        jButton44.setText("<html>Cadastro de<br>Materiais");
        jButton44.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44jButton20jButton1ActionPerformed(evt);
            }
        });

        jButton45.setBackground(new java.awt.Color(0, 0, 51));
        jButton45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton45.setForeground(new java.awt.Color(255, 255, 255));
        jButton45.setText("<html>Cadastro de<br>Funcionários");
        jButton45.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45jButton21jButton2ActionPerformed(evt);
            }
        });

        jButton46.setBackground(new java.awt.Color(0, 0, 51));
        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton46.setForeground(new java.awt.Color(255, 255, 255));
        jButton46.setText("<html>Cadastro de<br>Clinetes");
        jButton46.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46jButton22jButton3ActionPerformed(evt);
            }
        });

        jButton47.setBackground(new java.awt.Color(0, 0, 51));
        jButton47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton47.setForeground(new java.awt.Color(255, 255, 255));
        jButton47.setText("<html>Ordem de<br>Serviços");
        jButton47.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47jButton23jButton4ActionPerformed(evt);
            }
        });

        jButton48.setBackground(new java.awt.Color(0, 0, 51));
        jButton48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton48.setForeground(new java.awt.Color(255, 255, 255));
        jButton48.setText("<html>Cadastro de<br>Serviços");
        jButton48.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48jButton24jButton5ActionPerformed(evt);
            }
        });

        jButton49.setBackground(new java.awt.Color(204, 0, 0));
        jButton49.setForeground(new java.awt.Color(255, 255, 255));
        jButton49.setText("Sair");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(0, 0, 51));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Início");
        btnInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(16, 16, 16))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38))
                    .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton45, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                    .addComponent(jButton48, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnInicio)
                        .addGap(11, 11, 11)
                        .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(jButton49)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(599, Short.MAX_VALUE)))
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(308, 308, 308)
                    .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(448, Short.MAX_VALUE)))
        );

        tabelaClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Novo Serviço");

        jLabel6.setText("Descrição do Serviço");

        jLabel7.setText("Preço R$");

        jLabel8.setText("Código");

        jLabel19.setText("Estado");

        btnSalvarServico.setBackground(new java.awt.Color(153, 0, 153));
        btnSalvarServico.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarServico.setText("Salvar Serviço");
        btnSalvarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarServicoActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(0, 0, 204));
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Atualizar dados");

        btnEditar.setBackground(new java.awt.Color(0, 102, 0));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabelaClientesLayout = new javax.swing.GroupLayout(tabelaClientes);
        tabelaClientes.setLayout(tabelaClientesLayout);
        tabelaClientesLayout.setHorizontalGroup(
            tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaClientesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5))
            .addGroup(tabelaClientesLayout.createSequentialGroup()
                .addGap(607, 607, 607)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)))
            .addGroup(tabelaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabelaClientesLayout.createSequentialGroup()
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
            .addGroup(tabelaClientesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnSalvarServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addGap(119, 119, 119)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar))
        );
        tabelaClientesLayout.setVerticalGroup(
            tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaClientesLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(tabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarServico)
                    .addComponent(btnAtualizar)
                    .addComponent(jLabel2)
                    .addComponent(btnEditar))
                .addGap(144, 144, 144)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel31.setText("Serviços");

        jScrollPane3.setPreferredSize(new java.awt.Dimension(452, 200));

        tabelaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idTDS", "Código", "Descrição", "Preço"
            }
        ));
        jScrollPane3.setViewportView(tabelaServicos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cadastro de Serviços");

        jLabel4.setText("Gerencie os serviços ");

        jLabel1.setText("Pesquisar Serviço por código");

        btnPesquisar.setBackground(new java.awt.Color(102, 102, 102));
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnNovoServico.setBackground(new java.awt.Color(51, 51, 255));
        btnNovoServico.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoServico.setText("Novo Serviço");
        btnNovoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoServicoActionPerformed(evt);
            }
        });

        jLabel25.setText("Selecionar uma linha");

        btnExcluir.setBackground(new java.awt.Color(255, 0, 51));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(tabelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisarServico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovoServico)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)))
                        .addGap(237, 237, 237))))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisarServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnNovoServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(399, 399, 399))
        );

        jScrollPane1.setViewportView(jPanel18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton44jButton20jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44jButton20jButton1ActionPerformed
        CadastroMaterial mat = new CadastroMaterial(privilegio);
        mat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton44jButton20jButton1ActionPerformed

    private void jButton45jButton21jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45jButton21jButton2ActionPerformed
        CadastroFuncionarios func = new CadastroFuncionarios(privilegio);
        func.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton45jButton21jButton2ActionPerformed

    private void jButton46jButton22jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46jButton22jButton3ActionPerformed
        CadastroClientes cadCli = new CadastroClientes(privilegio);
        cadCli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton46jButton22jButton3ActionPerformed

    private void jButton47jButton23jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47jButton23jButton4ActionPerformed
        TelaOrdemServico os = new TelaOrdemServico(privilegio);
        os.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton47jButton23jButton4ActionPerformed

    private void jButton48jButton24jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48jButton24jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton48jButton24jButton5ActionPerformed

    private void btnSalvarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarServicoActionPerformed
        String strDescricao = txtDescricao.getText();
        String strPreco = txtPreco.getText();
        String strCodigo = txtCodigo.getText();
        
        if(strDescricao.trim().isEmpty() || strPreco.trim().isEmpty() || strCodigo.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchiodos");
        }
        
        if (!strPreco.matches("^[0-9]+(,[0-9]{1,2})?$")) {
             JOptionPane.showMessageDialog(this, "Formato inválido! Use formato: 0,00");
             return; 
        }
        String limpo = strPreco.replace(".", "").replace(",", ".");
         if (!strCodigo.matches("^[0-9]{4}$")) {
              JOptionPane.showMessageDialog(this,"Código Invalido, digite digite 4 caracteres de 0 a 9");
            return;
        }
        
        
        TipoDeServicoDao dao = new TipoDeServicoDao();
        TipoDeServico tds = new TipoDeServico();
        
        tds.setDescricao(strDescricao);
        try {
              tds.setPrecoServico(Double.parseDouble(limpo));
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ocorreu um erro na conersão do preço!");
          return;
        }
        try{
        tds.setCodigo(strCodigo);
        
        dao.salvar(tds);
        model();
        JOptionPane.showMessageDialog(this, "Serviço cadastrado com sucesso");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro inesperado, material não cadastrado");
        } 
        
    }//GEN-LAST:event_btnSalvarServicoActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Home home = new Home(privilegio);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton49ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String strPesquisar = txtPesquisarServico.getText();

        TipoDeServicoDao dao = new TipoDeServicoDao();
        TipoDeServico tipoServico = dao.consultar(strPesquisar);

        if(tipoServico == null){
            JOptionPane.showMessageDialog(this, "Serviço não encontrado");
        }else{
            idtds = tipoServico.getIdTds();
            txtDescricao.setText(tipoServico.getDescricao());

            txtPreco.setText(String.valueOf(tipoServico.getPrecoServico()));

            txtCodigo.setText(tipoServico.getCodigo());
    
            btnSalvarServico.setEnabled(false);

           // txtPesquisarServico.setEditable(false);
            txtDescricao.setEditable(false);
            txtPreco.setEditable(false);
            txtCodigo.setEditable(false);

        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoServicoActionPerformed
        txtPesquisarServico.setEditable(true);
        txtDescricao.setEditable(true);
        txtPreco.setEditable(true);
        txtCodigo.setEditable(true);
       
        txtPesquisarServico.setText("");
        txtDescricao.setText("");
        txtPreco.setText("");
        txtCodigo.setText("");
      
        btnSalvarServico.setEnabled(true);
    }//GEN-LAST:event_btnNovoServicoActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        String strDescricao = txtDescricao.getText();
        String strPreco = txtPreco.getText();
        String strCodigo = txtCodigo.getText();
      
        if(strDescricao.trim().isEmpty() || strPreco.trim().isEmpty() || strCodigo.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Todos os campos obrigatórios devem ser preenchidos");
            return;
        }

        if (!strPreco.matches("^[0-9]+(,[0-9]{1,2})?$")) {
            JOptionPane.showMessageDialog(this, "Formato inválido! Use formato: 0,00");
            return;
        }
        String limpo = strPreco.replace(".", "").replace(",", ".");
       
        if (!strCodigo.matches("^[0-9]{4}$")) {
            JOptionPane.showMessageDialog(this,"Código Invalido, digite digite 4 caracteres de 0 a 9");
            return;
        }

        TipoDeServicoDao dao = new TipoDeServicoDao();
        TipoDeServico tipoServ = new TipoDeServico();

        tipoServ.setDescricao(strDescricao);
        try {
            tipoServ.setPrecoServico(Double.parseDouble(limpo));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro na conersão do preço!");
            return;
        }
        try{
            tipoServ.setCodigo(strCodigo);
            tipoServ.setIdTds(idtds);

            dao.atualizar(tipoServ);

            model();
            JOptionPane.showMessageDialog(this, "Serviço atualizado com sucesso");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro inesperado, Serviço não atualizado");
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtPesquisarServico.setEditable(true);
        txtDescricao.setEditable(true);
        txtPreco.setEditable(true);
        txtCodigo.setEditable(true);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = tabelaServicos.getSelectedRow();
        TipoDeServicoDao dao = new TipoDeServicoDao();

        if (linhaSelecionada >= 0) {
            int idTDS = (int) tabelaServicos.getValueAt(linhaSelecionada, 0);
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir esta consulta?");

            if (resposta == JOptionPane.YES_OPTION) {

                dao.remover(idTDS);

                model();

                JOptionPane.showMessageDialog(this, "Item excluido com sucesso!");
            }

        } else {

            JOptionPane.showMessageDialog(this, "Selecione uma consulta na tabela para excluir.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroServicos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnNovoServico;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvarServico;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JPanel tabelaClientes;
    private javax.swing.JTable tabelaServicos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPesquisarServico;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
public void model() {
    DefaultTableModel model = (DefaultTableModel) tabelaServicos.getModel();
    TipoDeServicoDao dao = new TipoDeServicoDao();
    List<TipoDeServico> lista = dao.consultarTodos();
    
   
    if (lista == null || lista.isEmpty()) {
        System.out.println("DEBUG: A lista retornada pelo DAO está vazia.");
        return; 
    }
    
    model.setRowCount(0);
    DecimalFormat df = new DecimalFormat("#,##0.00");
    for (TipoDeServico tds : lista) {
        
        model.addRow(new Object[]{
            tds.getIdTds(),
            tds.getCodigo(),
            tds.getDescricao(),
            df.format(tds.getPrecoServico()),
            
        });
    }
    tabelaServicos.getColumnModel().getColumn(0).setMinWidth(0);
    tabelaServicos.getColumnModel().getColumn(0).setMaxWidth(0);
    tabelaServicos.getColumnModel().getColumn(0).setPreferredWidth(0);        


}


}