/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import br.com.solugem.model.Cargo;
import br.com.solugem.model.Empresa;
import br.com.solugem.model.Endereco;
import br.com.solugem.model.Funcionario;
import br.com.solugem.model.Telefone;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import solugemmDao.CargoDao;
import solugemmDao.EmpresaDao;
import solugemmDao.FuncionarioDao;


/**
 *
 * @author principal
 */
public class CadastroFuncionarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroFuncionarios.class.getName());

    /**
     * Creates new form CadastroFuncionarios
     */
    public CadastroFuncionarios() {
        initComponents();
         model3();
         txtPesquisarMatricula.setText("0001");
       
        carregarComboCargo();
        carregarComboEmpresas();
        btnAtualizar.setEnabled(false);
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
        @Override
        public void run() {
            model3();
        }
    });
        
    }
    char privilegio;
    public CadastroFuncionarios(char inicial){
        this();
        privilegio = inicial;
         switch (inicial) {
                case '2':
                System.out.println("Acesso: DONO");
                       
                break;
        
                case '1':
                System.out.println("Acesso: ATENDENTE ");
                // privilégios para atendentes estabelecidos pela documentação 
                btnSalvarFuncionario.setEnabled(false);
                btnNovoFuncionario.setEnabled(false);
                btnAtualizar.setEnabled(false);
                btnEditar.setEnabled(false);
                btnExcluir.setEnabled(false);
                
                break;
        
           }
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnCadMaterial = new javax.swing.JButton();
        btnCadFuncionario = new javax.swing.JButton();
        btnCadCliente = new javax.swing.JButton();
        btnOs = new javax.swing.JButton();
        btnCadServico = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        painel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbmEmpresa = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbmCargo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCasa = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtApartamento = new javax.swing.JTextField();
        txtBloco = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnSalvarFuncionario = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisarMatricula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnNovoFuncionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(0, 0, 51));

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Gestão");

        jLabel30.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));

        btnCadMaterial.setBackground(new java.awt.Color(0, 0, 51));
        btnCadMaterial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnCadMaterial.setText("<html>Cadastro de<br>Materiais");
        btnCadMaterial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMaterialjButton1ActionPerformed(evt);
            }
        });

        btnCadFuncionario.setBackground(new java.awt.Color(0, 0, 51));
        btnCadFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btnCadFuncionario.setText("<html>Cadastro de<br>Funcionários");
        btnCadFuncionario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncionariojButton2ActionPerformed(evt);
            }
        });

        btnCadCliente.setBackground(new java.awt.Color(0, 0, 51));
        btnCadCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCadCliente.setText("<html>Cadastro de<br>Clinetes");
        btnCadCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClientejButton3ActionPerformed(evt);
            }
        });

        btnOs.setBackground(new java.awt.Color(0, 0, 51));
        btnOs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOs.setForeground(new java.awt.Color(255, 255, 255));
        btnOs.setText("<html>Ordem de<br>Serviços");
        btnOs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsjButton4ActionPerformed(evt);
            }
        });

        btnCadServico.setBackground(new java.awt.Color(0, 0, 51));
        btnCadServico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadServico.setForeground(new java.awt.Color(255, 255, 255));
        btnCadServico.setText("<html>Cadastro de<br>Serviços");
        btnCadServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadServicojButton5ActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(204, 0, 0));
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(0, 0, 51));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Início");
        btnInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(16, 16, 16))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOs, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29))
                    .addComponent(btnCadFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(btnCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addComponent(btnCadServico, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnInicio)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(btnCadMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(btnSair)
                .addContainerGap(688, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(btnCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(599, Short.MAX_VALUE)))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(308, 308, 308)
                    .addComponent(btnCadServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(448, Short.MAX_VALUE)))
        );

        painel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Novo Funcionário");

        jLabel6.setText("Nome completo");

        jLabel7.setText("Telefone");

        jLabel8.setText("Email");

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Data de Nascimento");

        jLabel10.setText("CPF");

        jLabel11.setText("Matrícula");

        jLabel12.setText("Sexo");

        jLabel13.setText("Empresa");

        jLabel14.setText("Cargo");

        cbmCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmCargoActionPerformed(evt);
            }
        });

        jLabel15.setText("Endereço");

        jLabel16.setText("CEP");

        jLabel17.setText("Bairro");

        jLabel18.setText("Cidade");

        jLabel19.setText("Estado");

        jLabel20.setText("Rua");

        jLabel21.setText("Número");

        jLabel22.setText("Casa");

        jLabel23.setText("Apartamento");

        jLabel24.setText("Bloco");

        btnSalvarFuncionario.setBackground(new java.awt.Color(153, 0, 153));
        btnSalvarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarFuncionario.setText("Salvar Funcionário");
        btnSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFuncionarioActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(0, 0, 204));
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Atualizar dados");

        btnEditar.setBackground(new java.awt.Color(0, 102, 0));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel3Layout = new javax.swing.GroupLayout(painel3);
        painel3.setLayout(painel3Layout);
        painel3Layout.setHorizontalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(211, 211, 211))
            .addGroup(painel3Layout.createSequentialGroup()
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painel3Layout.createSequentialGroup()
                                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                        .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painel3Layout.createSequentialGroup()
                                    .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(painel3Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel12)))
                                .addGroup(painel3Layout.createSequentialGroup()
                                    .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbmEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))
                                    .addGap(18, 18, 18)
                                    .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(cbmCargo, 0, 207, Short.MAX_VALUE))))))
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5))
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel3Layout.createSequentialGroup()
                                .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(150, 150, 150)
                                .addComponent(jLabel17)))
                        .addGap(22, 22, 22)
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(txtApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnSalvarFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtualizar)))
                        .addGap(18, 18, 18)
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar))
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel3Layout.setVerticalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarFuncionario)
                    .addComponent(btnAtualizar)
                    .addComponent(jLabel2)
                    .addComponent(btnEditar))
                .addGap(39, 39, 39))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel31.setText("Funcionários cadastrados");

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricula", "Nome", "Cargo", "Empresa"
            }
        ));
        jScrollPane3.setViewportView(tabelaFuncionarios);

        jLabel25.setText("Selecionar uma linha");

        btnExcluir.setBackground(new java.awt.Color(255, 0, 51));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addGap(67, 67, 67))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(btnExcluir))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cadastro de Funcionários");

        jLabel4.setText("Gerencie os funcionários da empresa");

        jLabel1.setText("pesquisar funcionário por matrícula");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNovoFuncionario.setBackground(new java.awt.Color(51, 51, 255));
        btnNovoFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoFuncionario.setText("Novo Funcionário");
        btnNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(painel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)
                        .addComponent(btnNovoFuncionario)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btnNovoFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1297, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadMaterialjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMaterialjButton1ActionPerformed
        CadastroMaterial cadMat = new CadastroMaterial(privilegio);
        cadMat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadMaterialjButton1ActionPerformed

    private void btnCadFuncionariojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncionariojButton2ActionPerformed
        
    }//GEN-LAST:event_btnCadFuncionariojButton2ActionPerformed

    private void btnCadClientejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClientejButton3ActionPerformed
        CadastroClientes cadCli = new CadastroClientes(privilegio);
        cadCli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadClientejButton3ActionPerformed

    private void btnOsjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsjButton4ActionPerformed
        TelaOrdemServico os = new TelaOrdemServico(privilegio);
        os.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOsjButton4ActionPerformed

    private void btnCadServicojButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadServicojButton5ActionPerformed
        CadastroServicos cadServ = new CadastroServicos(privilegio);
        cadServ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadServicojButton5ActionPerformed

    private void btnSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFuncionarioActionPerformed
        String nome = txtNome.getText();
        String telefone = txtTelefone.getText();
        String email = txtEmail.getText();
        String cpf = txtCPF.getText();
        String data = "";
        
         try{
            txtDataNascimento.commitEdit();
            data = txtDataNascimento.getText().trim();
        }catch(java.text.ParseException e){
            JOptionPane.showMessageDialog(null, "Digite a data correta");
        }
       
        String matricula = txtMatricula.getText();
        String sexo = txtSexo.getText();
        Empresa empresaSelecionada = (Empresa) cbmEmpresa.getSelectedItem();
      
        
        Cargo cargoSelecionado = (Cargo) cbmCargo.getSelectedItem();
        
        
        String cep = txtCEP.getText();
        String bairro = txtBairro.getText();
        String cidade = txtCidade.getText();
        String estado = txtEstado.getText();
        String rua = txtRua.getText();
        String numero = txtNumero.getText();
        String casa = txtCasa.getText();
        String apartamento = txtApartamento.getText();
        String bloco = txtBloco.getText();
        
        
        
        if(nome.trim().isEmpty() || telefone.trim().isEmpty() || cep.trim().isEmpty()
        || bairro.trim().isEmpty() || cidade.trim().isEmpty()||estado.trim().isEmpty()||rua.trim().isEmpty()
        || numero.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos");
            return;
        }
        
        if (!numero.matches("^(?i)(SN|[0-9]+[\\s-]?[A-Za-z]?)$")) {
            JOptionPane.showMessageDialog(this,"Erro! Por favor, insira um número válido (ex: 123, 123-A ou SN)");
            return;
        }
        
        if (!telefone.matches("^[0-9]{10,11}$")) {
             JOptionPane.showMessageDialog(this, "O telefone deve conter apenas números (DDD + número) e ter entre 10 e 11 dígitos.");
             return;
        } 
        if (!data.matches("^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/[0-9]{4}$")) {
            JOptionPane.showMessageDialog(this,"Data inválida");
            return;
        }
        if (!cpf.matches("^[0-9]{11}$")) {
              JOptionPane.showMessageDialog(this,"CPF inválido");
              return;
        }
        if (!cep.matches("^[0-9]{5}-?[0-9]{3}$")) {
           JOptionPane.showMessageDialog(this, "CEP inválido! Use o formato 00000-000.");
           return;
        }
        if (!matricula.matches("^[0-9]{4}$")) {
          JOptionPane.showMessageDialog(this, "A matrícula deve conter exatamente 4 números!");
          return;
        }
        if (!sexo.matches("^[MmFf]$")) {
          JOptionPane.showMessageDialog(this, "Sexo inválido! Digite apenas M ou F.");
          return;
        }       
     try{   
        Funcionario func = new Funcionario();
        Endereco endereco = new Endereco();
        Telefone telefon = new Telefone();
        FuncionarioDao dao = new FuncionarioDao();
        
        endereco.setCep(cep);
        endereco.setBairro(bairro);
        endereco.setCidade(cidade);
        endereco.setEstado(estado);
        endereco.setRua(rua);
        endereco.setNumero(numero);
        endereco.setCasa(casa);
        endereco.setNumeroApartamento(apartamento);
        endereco.setBloco(bloco);
        
        telefon.setNumero(telefone);
        
        func.setNome(nome);
        func.setTelefome(telefon);
        func.setEmail(email);
        func.setIdentificacao(cpf);
        DateTimeFormatter formatadorBR = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNascimento = LocalDate.parse(data,formatadorBR);
        func.setDataNascimento(dataNascimento);
        func.setMatricula(matricula);
        func.setSexo(sexo);
        func.setEmpresa(empresaSelecionada);
        func.setCargo(cargoSelecionado);
        func.setEndereco(endereco);
        
        dao.salvar(func);
        model3();
        JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso");
     }catch(Exception e){
         JOptionPane.showMessageDialog(this, "Erro inesperado, cadastro não realizado");
     }    
       // -------------------------------------------------
     cbmCargo.setEnabled(false);
    }//GEN-LAST:event_btnSalvarFuncionarioActionPerformed

    private void cbmCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmCargoActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Home home = new Home(privilegio);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
       
        String nome = txtNome.getText();
        String telefone = txtTelefone.getText();
        String email = txtEmail.getText();
        String cpf = txtCPF.getText();
        String data = "";
        
         try{
            txtDataNascimento.commitEdit();
            data = txtDataNascimento.getText().trim();
        }catch(java.text.ParseException e){
            JOptionPane.showMessageDialog(null, "Digite a data correta");
        }
       
        String matricula = txtMatricula.getText();
        String sexo = txtSexo.getText();
        Empresa empresaSelecionada = (Empresa) cbmEmpresa.getSelectedItem();
      
        
        Cargo cargoSelecionado = (Cargo) cbmCargo.getSelectedItem();
        
        
        String cep = txtCEP.getText();
        String bairro = txtBairro.getText();
        String cidade = txtCidade.getText();
        String estado = txtEstado.getText();
        String rua = txtRua.getText();
        String numero = txtNumero.getText();
        String casa = txtCasa.getText();
        String apartamento = txtApartamento.getText();
        String bloco = txtBloco.getText();
        
        
        
        if(nome.trim().isEmpty() || telefone.trim().isEmpty() || cep.trim().isEmpty()
        || bairro.trim().isEmpty() || cidade.trim().isEmpty()||estado.trim().isEmpty()||rua.trim().isEmpty()
        || numero.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos");
            return;
        }
        
        if (!numero.matches("^(?i)(SN|[0-9]+[\\s-]?[A-Za-z]?)$")) {
            JOptionPane.showMessageDialog(this,"Erro! Por favor, insira um número válido (ex: 123, 123-A ou SN)");
            return;
        }
        
        if (!telefone.matches("^[0-9]{10,11}$")) {
             JOptionPane.showMessageDialog(this, "O telefone deve conter apenas números (DDD + número) e ter entre 10 e 11 dígitos.");
             return;
        } 
        if (!data.matches("^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/[0-9]{4}$")) {
            JOptionPane.showMessageDialog(this,"Data inválida");
            return;
        }
        if (!cpf.matches("^[0-9]{11}$")) {
              JOptionPane.showMessageDialog(this,"CPF inválido");
              return;
        }
        if (!cep.matches("^[0-9]{5}-?[0-9]{3}$")) {
           JOptionPane.showMessageDialog(this, "CEP inválido! Use o formato 00000-000.");
           return;
        }
        if (!matricula.matches("^[0-9]{4}$")) {
          JOptionPane.showMessageDialog(this, "A matrícula deve conter exatamente 4 números!");
          return;
        }
        if (!sexo.matches("^[MmFf]$")) {
          JOptionPane.showMessageDialog(this, "Sexo inválido! Digite apenas M ou F.");
          return;
        }       
     try{   
        Funcionario func = new Funcionario();
        Endereco endereco = new Endereco();
        Telefone tel = new Telefone();
        FuncionarioDao dao = new FuncionarioDao();
        
        endereco.setCep(cep);
        endereco.setBairro(bairro);
        endereco.setCidade(cidade);
        endereco.setEstado(estado);
        endereco.setRua(rua);
        endereco.setNumero(numero);
        endereco.setCasa(casa);
        endereco.setNumeroApartamento(apartamento);
        endereco.setBloco(bloco);
        
        tel.setNumero(telefone);
        
        func.setNome(nome);
        func.setTelefome(tel);
        func.setEmail(email);
        func.setIdentificacao(cpf);
        DateTimeFormatter formatadorBR = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNascimento = LocalDate.parse(data,formatadorBR);
        func.setDataNascimento(dataNascimento);
        func.setMatricula(matricula);
        func.setSexo(sexo);
        func.setEmpresa(empresaSelecionada);
        func.setCargo(cargoSelecionado);
        func.setEndereco(endereco);
        
        dao.atualizar(func);
        model3();
        btnSalvarFuncionario.setVisible(true);
        
        txtPesquisarMatricula.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtDataNascimento.setText("");
        txtCPF.setText("");
        txtMatricula.setText("");
        txtSexo.setText("");
        txtCEP.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtCasa.setText("");
        txtApartamento.setText("");
        txtBloco.setText("");
        
        JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso");
     }catch(Exception e){   
        JOptionPane.showMessageDialog(this,"Erro inesperado, funcionário não cadastrado");
     }    
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
         int linhaSelecionada = tabelaFuncionarios.getSelectedRow();
         FuncionarioDao dao = new FuncionarioDao();
           
           if (linhaSelecionada >= 0) {
        
            
                 int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir esta consulta?");
            
            if (resposta == JOptionPane.YES_OPTION) {
         
                dao.remover(linhaSelecionada);
                 
                model3();
                
            JOptionPane.showMessageDialog(this, "Item excluido com sucesso!");
            }
        
    } else {
        
        JOptionPane.showMessageDialog(this, "Selecione uma consulta na tabela para excluir.");
    }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             
        String strPesquisarMatricula = txtPesquisarMatricula.getText();
        
        
        FuncionarioDao dao = new FuncionarioDao();
        Funcionario funcionario = dao.consultar(strPesquisarMatricula);
        
        if(funcionario == null){
            JOptionPane.showMessageDialog(this, "Funcionário não encontrado");
        }else{
        
        txtNome.setText(funcionario.getNome());
        txtTelefone.setText(funcionario.getTelefome().getNumero());
        txtEmail.setText(funcionario.getEmail());
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtDataNascimento.setText(funcionario.getDataNascimento().format(formatador));
       // txtDataNascimento.setText(cliente.getDataNascimento().toString());
        txtCPF.setText(funcionario.getIdentificacao());
        txtSexo.setText(funcionario.getSexo());
        txtMatricula.setText(funcionario.getMatricula());
        txtCEP.setText(funcionario.getEndereco().getCep());
        txtBairro.setText(funcionario.getEndereco().getBairro());
        txtCidade.setText(funcionario.getEndereco().getCidade());
        txtEstado.setText(funcionario.getEndereco().getEstado());
        txtRua.setText(funcionario.getEndereco().getRua());
        txtNumero.setText(String.valueOf(funcionario.getEndereco().getNumero()));
        txtCasa.setText(funcionario.getEndereco().getCasa());
        txtApartamento.setText(funcionario.getEndereco().getNumeroApartamento());
        txtBloco.setText(funcionario.getEndereco().getBloco());
        cbmEmpresa.setSelectedItem(funcionario.getEmpresa());
      
        carregarComboCargo(funcionario.getCargo());
       
        btnSalvarFuncionario.setEnabled(false);
        
       // txtPesquisarMatricula.setEditable(false);
        txtNome.setEditable(false);
        txtTelefone.setEditable(false);
        txtEmail.setEditable(false);
        txtDataNascimento.setEditable(false);
        txtCPF.setEditable(false);
        txtMatricula.setEditable(false);
        txtSexo.setEditable(false);
        txtCEP.setEditable(false);
        txtBairro.setEditable(false);
        txtCidade.setEditable(false);
        txtEstado.setEditable(false);
        txtRua.setEditable(false);
        txtNumero.setEditable(false);
        txtCasa.setEditable(false);
        txtApartamento.setEditable(false);
        txtBloco.setEditable(false);
        
       
        cbmCargo.setEnabled(false); 
        if(privilegio == 2){
           btnAtualizar.setEnabled(true);
        } else{
                    btnAtualizar.setEnabled(false);
              }   
         
     }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFuncionarioActionPerformed
        cbmCargo.setEnabled(true);
        txtPesquisarMatricula.setEditable(true);
        txtNome.setEditable(true);
        txtTelefone.setEditable(true);
        txtEmail.setEditable(true);
        txtDataNascimento.setEditable(true);
        txtCPF.setEditable(true);
        txtMatricula.setEditable(true);
        txtSexo.setEditable(true);
        txtCEP.setEditable(true);
        txtBairro.setEditable(true);
        txtCidade.setEditable(true);
        txtEstado.setEditable(true);
        txtRua.setEditable(true);
        txtNumero.setEditable(true);
        txtCasa.setEditable(true);
        txtApartamento.setEditable(true);
        txtBloco.setEditable(true);
        
        txtPesquisarMatricula.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtDataNascimento.setText("");
        txtCPF.setText("");
        txtMatricula.setText("");
        txtSexo.setText("");
        txtCEP.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtCasa.setText("");
        txtApartamento.setText("");
        txtBloco.setText("");
        
        btnSalvarFuncionario.setEnabled(true);
        btnAtualizar.setEnabled(false);
        
    }//GEN-LAST:event_btnNovoFuncionarioActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtPesquisarMatricula.setEditable(true);
        txtNome.setEditable(true);
        txtTelefone.setEditable(true);
        txtEmail.setEditable(true);
        txtDataNascimento.setEditable(true);
        txtCPF.setEditable(true);
        txtMatricula.setEditable(true);
        txtSexo.setEditable(true);
        txtCEP.setEditable(true);
        txtBairro.setEditable(true);
        txtCidade.setEditable(true);
        txtEstado.setEditable(true);
        txtRua.setEditable(true);
        txtNumero.setEditable(true);
        txtCasa.setEditable(true);
        txtApartamento.setEditable(true);
        txtBloco.setEditable(true);
        btnAtualizar.setEnabled(true);
       
    
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroFuncionarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadCliente;
    private javax.swing.JButton btnCadFuncionario;
    private javax.swing.JButton btnCadMaterial;
    private javax.swing.JButton btnCadServico;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnNovoFuncionario;
    private javax.swing.JButton btnOs;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvarFuncionario;
    private javax.swing.JComboBox<String> cbmCargo;
    private javax.swing.JComboBox<String> cbmEmpresa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel painel3;
    private javax.swing.JTable tabelaFuncionarios;
    private javax.swing.JTextField txtApartamento;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBloco;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCasa;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisarMatricula;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

 public void carregarComboCargo(){
     CargoDao dao = new CargoDao();
     List<Cargo> lista = dao.listarTodos();
     cbmCargo.removeAllItems();
     DefaultComboBoxModel model = new DefaultComboBoxModel<>();
     for(Cargo c: lista){
         model.addElement(c);
     }
   
     cbmCargo.setModel((DefaultComboBoxModel) model);
 }
 // comboBox alternativo ------------------------------------------
 
 public void carregarComboCargo(Cargo cargoSelecionado) {
    CargoDao dao = new CargoDao();
    List<Cargo> lista = dao.listarTodos();
   
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
   
    for (Cargo c : lista) {
       
        model.addElement(c.getCargo());
    }
 
    if (cargoSelecionado != null) {
        model.setSelectedItem(cargoSelecionado);
    }
  
    cbmCargo.setModel(model);
}
 
 // -------------------------------------------------------------
 public void carregarComboEmpresas() {
    EmpresaDao dao = new EmpresaDao();
    //List<Empresa> lista = dao.listarTodos();
    var lista = dao.listarTodos();
   
    DefaultComboBoxModel <Empresa> model= new DefaultComboBoxModel();
    
    for (Empresa e : lista) {
        model.addElement(e);
    }
  
   cbmEmpresa.setModel((DefaultComboBoxModel) model);
   
}
 
 public void model3() {
    DefaultTableModel model = (DefaultTableModel) tabelaFuncionarios.getModel();
    FuncionarioDao dao = new FuncionarioDao();
    List<Funcionario> lista = dao.consultarTodos();
    
   
    if (lista == null || lista.isEmpty()) {
        System.out.println("DEBUG: A lista retornada pelo DAO está vazia.");
        return; 
    }
    
    model.setRowCount(0);
    
    for (Funcionario f : lista) {
        // Proteção contra valores nulos nas colunas
        model.addRow(new Object[]{
            f.getMatricula(),
            f.getNome(),
            (f.getCargo() != null) ? f.getCargo().toString() : "-",
            (f.getEmpresa() != null) ? f.getEmpresa().toString() : "-"
        });
    }
}
 

}
